#pragma region RAYTRACING
VK_DEVICE_PROC_ADDR(GetAccelerationStructureBuildSizesKHR)
VK_DEVICE_PROC_ADDR(CreateAccelerationStructureKHR)
VK_DEVICE_PROC_ADDR(CmdBuildAccelerationStructuresKHR)
VK_DEVICE_PROC_ADDR(GetRayTracingShaderGroupHandlesKHR)
VK_DEVICE_PROC_ADDR(CreateRayTracingPipelinesKHR)
VK_DEVICE_PROC_ADDR(DestroyAccelerationStructureKHR)
#pragma endregion