#pragma region RAYTRACING
VK_PROC_ADDR(GetAccelerationStructureBuildSizesKHR)
VK_PROC_ADDR(GetAccelerationStructureDeviceAddressKHR)
VK_PROC_ADDR(GetBufferDeviceAddressKHR)
VK_PROC_ADDR(GetRayTracingShaderGroupHandlesKHR)

VK_PROC_ADDR(CreateAccelerationStructureKHR)
VK_PROC_ADDR(CreateRayTracingPipelinesKHR)

VK_PROC_ADDR(BuildAccelerationStructuresKHR)

VK_PROC_ADDR(DestroyAccelerationStructureKHR)

VK_PROC_ADDR(CmdBuildAccelerationStructuresKHR)
VK_PROC_ADDR(CmdTraceRaysKHR)
#pragma endregion