#pragma region RAYTRACING
VK_PROC_ADDR(GetAccelerationStructureBuildSizesKHR)
VK_PROC_ADDR(GetAccelerationStructureDeviceAddressKHR)
VK_PROC_ADDR(GetRayTracingShaderGroupHandlesKHR)

VK_PROC_ADDR(CreateAccelerationStructureKHR)
VK_PROC_ADDR(CreateRayTracingPipelinesKHR)

VK_PROC_ADDR(BuildAccelerationStructuresKHR)

VK_PROC_ADDR(DestroyAccelerationStructureKHR)

VK_PROC_ADDR(CmdBuildAccelerationStructuresKHR)
VK_PROC_ADDR(CmdTraceRaysKHR)
VK_PROC_ADDR(CmdTraceRaysIndirectKHR)

VK_PROC_ADDR(CmdWriteAccelerationStructuresPropertiesKHR)
VK_PROC_ADDR(CmdCopyAccelerationStructureKHR)

VK_PROC_ADDR(CmdSetRayTracingPipelineStackSizeKHR)
#pragma endregion