VK_PROC_ADDR(CreateDevice)
VK_PROC_ADDR(DestroyInstance)
VK_PROC_ADDR(EnumerateDeviceExtensionProperties)
VK_PROC_ADDR(EnumerateDeviceLayerProperties)
VK_PROC_ADDR(EnumeratePhysicalDevices)
VK_PROC_ADDR(GetDeviceProcAddr)
VK_PROC_ADDR(GetPhysicalDeviceFeatures)
VK_PROC_ADDR(GetPhysicalDeviceFormatProperties)
VK_PROC_ADDR(GetPhysicalDeviceMemoryProperties)
VK_PROC_ADDR(GetPhysicalDeviceProperties)
VK_PROC_ADDR(GetPhysicalDeviceQueueFamilyProperties)
VK_PROC_ADDR(GetPhysicalDeviceImageFormatProperties)

//!< VK_KHR_SURFACE_EXTENSION_NAME
VK_PROC_ADDR(DestroySurfaceKHR)
VK_PROC_ADDR(GetPhysicalDeviceSurfaceCapabilitiesKHR)
VK_PROC_ADDR(GetPhysicalDeviceSurfaceFormatsKHR)
VK_PROC_ADDR(GetPhysicalDeviceSurfacePresentModesKHR)
VK_PROC_ADDR(GetPhysicalDeviceSurfaceSupportKHR)

//!< VK_KHR_WIN32_SURFACE_EXTENSION_NAME
#ifdef VK_USE_PLATFORM_WIN32_KHR
VK_PROC_ADDR(CreateWin32SurfaceKHR)
#endif