#define RS "RootFlags(DENY_VERTEX_SHADER_ROOT_ACCESS|DENY_HULL_SHADER_ROOT_ACCESS|DENY_DOMAIN_SHADER_ROOT_ACCESS|DENY_PIXEL_SHADER_ROOT_ACCESS),"\
			"DescriptorTable(CBV(b0, space=0), visibility=SHADER_VISIBILITY_GEOMETRY)"
